name: Multi-Platform Docker Build

on:
  push:
    branches: [ "main" ]
    paths: 
      - "docker/**"
      - "dist/**"
      - "index.html"
  workflow_dispatch:
  schedule:
    - cron: "* 8 * * *"

env:
  DOCKER_USER: secrets.DOCKERHUB_USERNAME
  CONTAINER_NAME: "mind-map"
  UPSTREAM_REPO: "wanglin2/mind-map"
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  GOTIFY_SERVER: ${{ secrets.GOTIFY_SERVER }}
  GOTIFY_TOKEN: ${{ secrets.GOTIFY_TOKEN }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check-upstream:
    runs-on: ubuntu-22.04
    outputs:
      has_updates: ${{ steps.compare.outputs.has_updates }}
    steps:
      - name: Checkout Fork Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git
          git fetch upstream

      - name: Compare commits
        id: compare
        run: |
          UPSTREAM_COMMIT=$(git rev-parse upstream/main)
          FORK_COMMIT=$(git rev-parse origin/main)
          echo "upstream_commit=$UPSTREAM_COMMIT" >> $GITHUB_OUTPUT
          echo "fork_commit=$FORK_COMMIT" >> $GITHUB_OUTPUT
          if [ "$UPSTREAM_COMMIT" != "$FORK_COMMIT" ]; then
            echo "has_updates=true" >> $GITHUB_OUTPUT
            echo "Detected update: $UPSTREAM_COMMIT → $FORK_COMMIT"
          else
            echo "has_updates=false" >> $GITHUB_OUTPUT
          fi

      - name: Sync updates
        if: steps.compare.outputs.has_updates == 'true'
        run: |
          git merge --ff-only upstream/main
          git push origin main

  build-and-push:
    needs: check-upstream
    if: needs.check-upstream.outputs.has_updates == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set build date
        run: echo "TAG=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (Multi-Arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/multi-platform/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ env.DOCKER_USER }}/${{ env.CONTAINER_NAME }}:${{ env.TAG }}-debug
            ${{ env.DOCKER_USER }}/${{ env.CONTAINER_NAME }}:latest-debug
          cache-from: type=gha
          cache-to: type=gha,mode=max
